<a href="https://colab.research.google.com/github/vamshiG1998/DataScience_2501/blob/main/DS_08112025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy

import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(3,16,3)
print(arr)

[ 3  6  9 12 15]


In [ ]:
arr = np.arange(11,1,-2)
print(arr)

[11  9  7  5  3]


In [ ]:
iden = np.identity(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
iden = np.eye(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
zero_shape = np.zeros((3,4))
print(zero_shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
one = np.ones((2,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
array1 = np.array([[10,12,14],[14,12,10]])
print(array1)

[[10 12 14]
 [14 12 10]]


In [ ]:
shape_array1 = np.shape(array1) #shape of the array
print(shape_array1)

(2, 3)


In [ ]:
print(array1.size) #will give the elements count of array

6


In [ ]:
print(array1.ndim) #will give you the number of dimensions(axes) of the array

2


In [ ]:
array2 = np.ones(6)
print(array2)

[1. 1. 1. 1. 1. 1.]


In [ ]:
array2_reshape = array2.reshape(3,2)
print(array2_reshape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
zero1 = np.zeros(7)
print(zero1)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(zero1.reshape(1,1))

ValueError: cannot reshape array of size 7 into shape (1,1)

In [ ]:
trans = np.array([[1,3,5],[7,9,11]])

In [ ]:
print(trans.T)

[[ 1  7]
 [ 3  9]
 [ 5 11]]


In [ ]:
print(trans.flatten())

[ 1  3  5  7  9 11]


In [ ]:
print(trans[0][2])

5


In [ ]:
index = np.array([[[2,4],[6,8],[10,12]]])


In [ ]:
print(index[0][1][1])
print(index[0][1])
print(index[0][2])

8
[6 8]
[10 12]


In [ ]:
arr2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

In [ ]:
print(arr2[0][1][1])
print(arr2[1][0][1])

40
60


In [ ]:
add = arr2[0][1][0] + arr2[1][1][1]
print(add)

110


In [ ]:
prod = arr2[0][0][0] * 11.1
print(prod)

111.0


In [ ]:
#Advacne python

In [ ]:
s = "Data Science"

print(s[:])

Data Science


In [ ]:
print(s[1:9:2])

aaSi


In [ ]:
array1 = np.array([1,2,3,4])
array2 = np.array([[1,3,5],[7,9,11]])

In [ ]:
print(array1[1:3])

[2 3]


In [ ]:
print(array1[4:1:-1])

[4 3]


In [ ]:
print(array2[1:])

[[ 7  9 11]]


In [ ]:
print(array2[0][0:2])

[1 3]


In [ ]:
print(array2[1][0:3])

[ 7  9 11]


In [ ]:
print(array1[array1 > 2])

[3 4]


In [ ]:
print(array1)

[1 2 3 4]


In [ ]:
print(array1[[0,3,1]])

[1 4 2]


In [ ]:
print(array1[2])

3


In [ ]:
print(array1[(array1 % 2)==0])

[2 4]


In [ ]:
print(array1[array1 % 2])

[2 1 2 1]


In [ ]:
a = np.array([1,2,3])
b = np.array([11,12,13])

In [ ]:
print(a+b)

[12 14 16]


In [ ]:
print(a-b)

[-10 -10 -10]


In [ ]:
print(a*b)

[11 24 39]


In [ ]:
print((a+b)*11)

[132 154 176]


In [ ]:
print(array1.sum())

10


In [ ]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [ ]:
print(np.divide(a,b))

[0.09090909 0.16666667 0.23076923]


In [ ]:
print(a.sum())
print(np.double(a))

6
[1. 2. 3.]


In [ ]:
print(a.max())
print(np.maximum(a,b))

3
[11 12 13]


In [ ]:
print(array2)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
print(array2.sum())

36


In [ ]:
print(array2.mean())

6.0


In [ ]:
print(array2.mean(axis=0))

[4. 6. 8.]


In [ ]:
print(array2.mean(axis=1))

[3. 9.]


In [ ]:
print(a,b)

[1 2 3] [11 12 13]


In [ ]:
print(np.hstack((a,b))) #combines the array column wise, horizontal stack

[ 1  2  3 11 12 13]


In [ ]:
print(np.vstack((b,a))) #combines the array row wise, vertical stack
print(np.vstack((a,b)))

[[11 12 13]
 [ 1  2  3]]
[[ 1  2  3]
 [11 12 13]]


In [ ]:
print(array1)
print(array2)

[1 2 3 4]
[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
print(np.hsplit(array1,2))

[array([1, 2]), array([3, 4])]


In [ ]:
print(np.hsplit(array2,3))

[array([[1],
       [7]]), array([[3],
       [9]]), array([[ 5],
       [11]])]


In [ ]:
print(np.vsplit(array2,2))

[array([[1, 3, 5]]), array([[ 7,  9, 11]])]


In [ ]:
array3 = np.array([1,2,3,5,6])

In [ ]:
new_array3 = np.insert(array3,3,4)
print(new_array3)

[1 2 3 4 5 6]


In [ ]:
new_array3 = np.delete(array3,3)
print(new_array3)

[1 2 3 6]


In [ ]:
new_array3 = np.insert(array3,0,10)
print(new_array3)

[10  1  2  3  5  6]


In [ ]:
print(a)
print(b)


[1 2 3]
[11 12 13]


In [ ]:
print(np.dot(a,b))

74


In [ ]:
mat = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]
