<a href="https://colab.research.google.com/github/vamshiG1998/DataScience_2501/blob/main/DS_08112025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy

import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
arr = np.arange(3,16,3)
print(arr)

[ 3  6  9 12 15]


In [8]:
arr = np.arange(11,1,-2)
print(arr)

[11  9  7  5  3]


In [3]:
iden = np.identity(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
iden = np.eye(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
zero_shape = np.zeros((3,4))
print(zero_shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
one = np.ones((2,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
array1 = np.array([[10,12,14],[14,12,10]])
print(array1)

[[10 12 14]
 [14 12 10]]


In [14]:
shape_array1 = np.shape(array1) #shape of the array
print(shape_array1)

(2, 3)


In [15]:
print(array1.size) #will give the elements count of array

6


In [18]:
print(array1.ndim) #will give you the number of dimensions(axes) of the array

2


In [34]:
array2 = np.ones(6)
print(array2)

[1. 1. 1. 1. 1. 1.]


In [42]:
array2_reshape = array2.reshape(3,2)
print(array2_reshape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [43]:
zero1 = np.zeros(7)
print(zero1)

[0. 0. 0. 0. 0. 0. 0.]


In [45]:
print(zero1.reshape(1,1))

ValueError: cannot reshape array of size 7 into shape (1,1)

In [50]:
trans = np.array([[1,3,5],[7,9,11]])

In [51]:
print(trans.T)

[[ 1  7]
 [ 3  9]
 [ 5 11]]


In [52]:
print(trans.flatten())

[ 1  3  5  7  9 11]


In [58]:
print(trans[0][2])

5


In [60]:
index = np.array([[[2,4],[6,8],[10,12]]])


In [73]:
print(index[0][1][1])
print(index[0][1])
print(index[0][2])

8
[6 8]
[10 12]


In [75]:
arr2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

In [79]:
print(arr2[0][1][1])
print(arr2[1][0][1])

40
60


In [82]:
add = arr2[0][1][0] + arr2[1][1][1]
print(add)

110


In [84]:
prod = arr2[0][0][0] * 11.1
print(prod)

111.0
